### ISSUE TITLE
add function(/* foo */) {}

### ISSUE THREAD

**Issue by flying-sheep** [michaelficarra/everything.js#18]
i saw acorn failing on this so maybe it would be a good idea to include it.

**Comment by michaelficarra** [comment]
That's not valid on its own. Also, typically I avoid testing combinations of productions. We already have function expressions with no parameters and multi-line comments individually.

**Comment by flying-sheep** [comment]
well, but the only way to test comments within parameter declarations is a context where parameter declarations are valid…

**Comment by michaelficarra** [comment]
But as I said, "comments within parameter declarations" is a combination of two things we already have: comments and (empty) parameter lists. We don't typically aspire to test all combinations of productions.

**Comment by flying-sheep** [comment]
ok
