### ISSUE TITLE
BSD license violating

### ISSUE THREAD

**Issue by lucascastro** [michaelficarra/everything.js#19]
You' are violating the license.
Your tarball isn't shipping a verbatim copy of it, and your copyright owner  definition is mistaken. 
take a look at template. 

https://opensource.org/licenses/BSD-3-Clause

Please I need this fixed to release at Debian GNU/Linux.

**Comment by michaelficarra** [comment]
@lucascastro Needs more info. What tarball? What is wrong with the license? It all looks fine to me.
