### ISSUE TITLE
add ES6 version

### ISSUE THREAD

**Issue by michaelficarra** [michaelficarra/everything.js#6]

**Comment by RReverser** [comment]
@michaelficarra Just figured out that I need this as well.

**Comment by sebmck** [comment]
@RReverser Likewise, anything we can do to help @michaelficarra?

**Comment by michaelficarra** [comment]
I'm going to start on this now. What are your plans with it?

**Comment by RReverser** [comment]
Testing traversals, transpilation and other stuff where exact code does not matter but syntax coverage does.

**Comment by michaelficarra** [comment]
Ah, that relates to #8. I'd love to get a PR for that so we can see if we're missing anything in everything.js.

**Comment by michaelficarra** [comment]
Okay, `/es6.js` should now cover all ES6 productions. Let me know if it does not or if there are any bugs. When the Shift parser is done, we'll run it over `/es6.js`. Once we feel comfortable with it, I'll cut a major release and switch over the `main` field in `/package.json` from `/es5.js` to `/es6.js`.

**Comment by RReverser** [comment]
@michaelficarra Thanks!
